#!/usr/bin/python
import time
import os.path


def main():
    if not os.path.exists("numbers.txt"):
        with open('numbers.txt', 'w') as fout:
            data.append("Guten Tag\n")
            fout.writelines(data)
#     while True:
#         try:
#             CurrentNumber=int(raw_input('Wartenummer:'))
#             if CurrentNumber == 999:
#                 break
#             if os.path.exists("numbers.txt"):
#                 Counter = 0
#                 f = open("numbers.txt", "r")
#                 Content = f.read()
#                 CoList = Content.split("\n") 
#                 for i in CoList: 
#                     if i: 
#                         Counter += 1
#                 if Counter == 15:
#                     with open('numbers.txt', 'r') as fin:
#                         data = fin.read().splitlines(True)
#                     with open('numbers.txt', 'w') as fout:
#                         data.append(str(CurrentNumber) + "\n")
#                         fout.writelines(data[1:])
#                 else:
#                     with open('numbers.txt', 'r') as fin:
#                         data = fin.read().splitlines(True)
#                     with open('numbers.txt', 'w') as fout:
#                         data.append(str(CurrentNumber) + "\n")
#                         fout.writelines(data)
#             else:
#                 with open('numbers.txt', 'w') as fout:
#                     data.append("Guten Tag\n")
#                     fout.writelines(data)
#         except ValueError:
#             break

# def main():
#     CurrentNumber = 0
#     while 1:
#         CurrentNumber = CurrentNumber +1
#         if os.path.exists("numbers.txt"):
#             Counter = 0
#             f = open("numbers.txt", "r")
#             Content = f.read()
#             CoList = Content.split("\n") 
#             for i in CoList: 
#                 if i: 
#                     Counter += 1
#             if Counter == 15:
#                 with open('numbers.txt', 'r') as fin:
#                     data = fin.read().splitlines(True)
#                 with open('numbers.txt', 'w') as fout:
#                     data.append(str(CurrentNumber) + "\n")
#                     fout.writelines(data[1:])
#             else:
#                 with open('numbers.txt', 'r') as fin:
#                     data = fin.read().splitlines(True)
#                 with open('numbers.txt', 'w') as fout:
#                     data.append(str(CurrentNumber) + "\n")
#                     fout.writelines(data)
#         else:
#             with open('numbers.txt', 'w') as fout:
#                 data.append("1\n")
#                 fout.writelines(data)
#         time.sleep(1)


# f = open("kantinendisplay/numbers.txt", "r")
# Counter = 0

# with open('kantinendisplay/numbers.txt', 'r') as fin:
#     data = fin.read().splitlines(True)
# with open('kantinendisplay/numbers.txt', 'w') as fout:
#     fout.writelines(data[1:])
    
# Content = f.read() 
# CoList = Content.split("\n") 

# for i in CoList: 
#     if i: 
#         Counter += 1

# print(Content)
# print(Counter)
    
if __name__ == "__main__":
    main()