#!/usr/bin/python
import time
import os.path

def main():
    CurrentNumber = 0
    while 1:
        CurrentNumber = CurrentNumber +1
        if os.path.exists("numbers.txt"):
            Counter = 0
            f = open("numbers.txt", "r")
            Content = f.read()
            CoList = Content.split("\n") 
            for i in CoList: 
                if i: 
                    Counter += 1
            if Counter == 5:
                with open('numbers.txt', 'r') as fin:
                    data = fin.read().splitlines(True)
                with open('numbers.txt', 'w') as fout:
                    data.append(str(CurrentNumber) + "\n")
                    fout.writelines(data[1:])
            else:
                with open('numbers.txt', 'r') as fin:
                    data = fin.read().splitlines(True)
                with open('numbers.txt', 'w') as fout:
                    data.append(str(CurrentNumber) + "\n")
                    fout.writelines(data)
        else:
            with open('numbers.txt', 'w') as fout:
                data.append("1\n")
                fout.writelines(data)
        time.sleep(1)


# f = open("kantinendisplay/numbers.txt", "r")
# Counter = 0

# with open('kantinendisplay/numbers.txt', 'r') as fin:
#     data = fin.read().splitlines(True)
# with open('kantinendisplay/numbers.txt', 'w') as fout:
#     fout.writelines(data[1:])
    
# Content = f.read() 
# CoList = Content.split("\n") 

# for i in CoList: 
#     if i: 
#         Counter += 1

# print(Content)
# print(Counter)
    
# while True:
#     try:
#         mode=int(raw_input('Wartenummer:'))
#         if mode == 999:
#             break
#         print mode
#     except ValueError:
#         break

if __name__ == "__main__":
    main()